# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NajamDemoFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NajamDemoFramework
    pod 'AFNetworking'

  target 'NajamDemoFrameworkTests' do
    # Pods for testing
  end

end
